import {
  BRAND,
  CONTACT_SERVICES,
  DIRECTIONS,
  EXAM_PRICES,
  FAQ,
  FORMATS,
  GALLERY,
  GERMAN_DIRECTION,
  LESSON_STEPS,
  NAV,
  PACKAGES,
  PRICING_INTRO,
  PRICING_TABS,
  STATS,
  TEACHER_LANG_TABS,
  TEACHERS,
} from '@/app/brand'
import type { SiteContent } from './types'

export function getDefaultContent(): SiteContent {
  return {
    brand: {
      name: BRAND.name,
      phone: BRAND.phone,
      email: BRAND.email,
      address: BRAND.address,
      city: BRAND.city,
      telegram: BRAND.telegram,
      logo: BRAND.logo,
      navCta: 'Записатись',
    },
    nav: NAV.map((item) => ({ ...item })),
    hero: {
      headlineLine1: BRAND.headline[0]!,
      headlineMiddle: 'у ',
      highlight: BRAND.highlight,
      headlineLine3: BRAND.headline[2]!,
      role: BRAND.role,
      cta: 'Записатись на заняття',
      heroImage: BRAND.heroImage,
      heroImageAlt: 'Заняття у школі іноземних мов LEXI.education',
      stats: STATS.map((item) => ({ ...item })),
    },
    directions: {
      heading: { line1: 'Напрями', line2Em: 'навчання' },
      lead: 'Оберіть мову, з якої хочете почати. Зараз відкрита німецька — інші напрями з’являться незабаром.',
      ctaMore: 'Детальніше',
      ctaSoon: 'Скоро відкриємо',
      items: DIRECTIONS.map((item) => ({ ...item })),
    },
    formats: {
      heading: { line1: 'Формати', line2Em: 'навчання' },
      lead: 'Від індивідуальних занять до розмовного клубу — обирайте темп і формат, який підходить саме вам. Або почніть із безкоштовного пробного заняття.',
      items: FORMATS.map((item) => ({ ...item, body: [...item.body] })),
    },
    pricing: {
      heading: { line1: 'Вартість', line2Em: 'навчання' },
      intro: PRICING_INTRO,
      trialBadge: '🔥 FREE',
      trialPrice: '0 грн',
      trialTitle: 'Пробне заняття — безкоштовно',
      trialText: 'Визначимо рівень, обговоримо цілі та підберемо формат.',
      trialCta: 'Записатись',
      comboNote: 'При навчанні 2 рази на тиждень у кожному форматі — до 16 занять на місяць.',
      packagesTitle: 'Пакети зі знижкою',
      packagesHint: 'Sprachklub: 8 занять −5% · 12 занять −8%',
      helpTitle: 'Не знаєте, який формат обрати?',
      helpText: 'Почніть із безкоштовного пробного заняття.',
      helpCta: 'Записатись на пробне',
      tabs: JSON.parse(JSON.stringify(PRICING_TABS)),
      examPrices: {
        headers: [...EXAM_PRICES.headers],
        rows: EXAM_PRICES.rows.map((row) => [...row]),
      },
      packages: JSON.parse(JSON.stringify(PACKAGES)),
    },
    lesson: {
      heading: { line1: 'Почніть із', line2Em: 'пробного' },
      lead: 'Пробне заняття — безкоштовне. Ви не повинні самостійно вирішувати, який формат вам потрібен — ми допоможемо підібрати його разом.',
      cta: 'Записатись на пробне заняття',
      steps: LESSON_STEPS.map((item) => ({ ...item })),
    },
    gallery: {
      heading: { line1: 'Атмосфера', line2Em: 'LEXI' },
      lead: 'Невеликі групи, живе спілкування й тепло — так виглядає навчання у нас.',
      lightboxLine1: 'Атмосфера',
      lightboxEm: 'LEXI',
      items: GALLERY.map((item) => ({ ...item })),
    },
    faq: {
      heading: { line1: 'Часті', line2Em: 'питання' },
      lead: 'Короткі відповіді про формати, пробне заняття, групи та пакети.',
      telegramLabel: 'Залишились питання?',
      telegramText: 'Напишіть нам у Telegram — відповімо швидко та допоможемо підібрати формат.',
      telegramBtn: 'Написати в Telegram',
      items: FAQ.map((item) => ({ ...item })),
    },
    teachers: {
      heading: { line1: 'Наші викладачі — свої!', line2Em: 'Вам точно буде комфортно' },
      cardMore: 'Детальніше',
      experiencePrefix: 'Досвід:',
      ctaTitle: 'Хочете познайомитись на пробному занятті?',
      ctaText: 'Залиште заявку — підберемо зручний час і викладача під вашу дитину.',
      ctaBtn: 'Записатись',
      tabs: TEACHER_LANG_TABS.map((item) => ({ ...item })),
      items: TEACHERS.map((item) => ({ ...item })),
    },
    germanDirection: {
      ...GERMAN_DIRECTION,
      heroCta: 'Записатись на пробне',
      processCta: 'Записатись',
      process: GERMAN_DIRECTION.process.map((item) => ({ ...item })),
    },
    contact: {
      titleLine1: 'LEXI',
      titleLine2: 'EDUCATION',
      hookText: 'отримай',
      hookEm: 'безкоштовне',
      hookSuffix: 'заняття',
    },
    contactServices: [...CONTACT_SERVICES],
  }
}
